@startuml
participant 开发人员
==家族长创建家族==
家族长 -> pp家族系统:创建家族
pp家族系统 -->家族长:创建成功
pp家族系统 -> 签约dc:认证企业信息
pp家族系统 -> 签约dc:认证银行卡信息
note right of 签约dc
如果上上签不支持
需要后台直接通过
end note
签约dc --> pp家族系统:认证成功
|||
==同步数据到签约系统==
开发人员 -> pp家族系统:请求接口录入合同信息
pp家族系统 ->签约dc:生成合同信息
note right:直接插入contract表,状态为签约成功
|||
==同步数据到结算==
pp家族系统 -> 清结算:运营设置税率并同步数据
pp家族系统 -> 清结算:定时同步家族的主播给结算
@enduml