@startmindmap
* 项目
** app_live_main
*** lz_live_room
**** lz_studio
**** lz_live_category
**** lz_pp_search
**** lz_common_commservice
**** lz_live_amusement
**** lz_live_oss_online
*** lz_studio
**** lz_comment
**** lz_live_gifteffect
**** lz_live_popularity
**** lz_pp_play_game
**** lz_push_appproxy_online
**** lz_live_gift
**** lz_live_rank
**** lz_pp_account
**** lz_live_room
**** lz_msg
*** lz_pp_play_game
**** lz_live_pp_common
**** lz_live_amusement
**** lz_live_call
**** lz_live_room
*** lz_live_oss_online
**** lz_live_kylin_home
**** lz_live_bubble_common
**** lz_vod_label
**** lz_common_commservice
**** lz_live_artificialrcmd
**** lz_live_room
**** lz_live_pp_core
**** lz_payment
**** lz_live_medal
**** lz_rec_recommend_platform_model_live
**** lz_live_popularity_guard
**** lz_growth_adfilter
**** lz_live_category
**** lz_sns_relation
*** lz_live_data
**** lz_live_battle
**** lz_live_amusement
**** lz_pp_vip
**** lz_live_room
*** lz_live_pp_common
**** lz_trend
**** lz_pp_account
*** lz_live_common_amusement
**** lz_sns_voicefriend
**** lz_live_amusement_activity
**** lz_live_popularity
**** lz_live_prop
**** lz_live_broadcast
**** lz_datacenter_chat_online
**** lz_live_avatar_widget_common
**** lz_live_gift
**** lz_pp_account
*** lz_live_call
*** lz_live_popularity_prop
*** lz_live_enternotice
*** lz_live_amusement
*** lz_pp_wealth
*** lz_pp_vip
*** lz_live_rank
**** lz_family
**** lz_live_room
*** lz_live_gift
**** lz_live_middle_prop
**** lz_vod_label
**** lz_common_usercenter
**** lz_live_room
*** lz_payment
**** lz_studio
**** lz_family
**** lz_user_verify
**** lz_live_net_signing
**** lz_live_rank
***** lz_family
***** lz_live_room
**** lz_msg
**** lz_live_gifteffect
**** lz_pp_wealth
**** lz_live_amusement
**** lz_pp_account
**** lz_rec_live_revenue_lucky_bag
*** lz_pp_account
@endmindmap