@startmindmap
* 项目
** app_live_trade
*** lz_live_trade
**** lz_common_trade_kylin
** app_sns
*** lz_comment
*** lz_live_operating_assistant
*** lz_live_kylin_home
*** lz_voice
*** ad_content
*** lz_live_room
*** lz_payment
*** lz_live_activity
**** lz_studio
**** lz_datacenter_chat_online
**** lz_live_battle
**** lz_common_usercenter
**** lz_pp_chat
**** lz_pp_account
**** lz_live_room
**** lz_live_rcmd_distribute
*** lz_studio
*** lz_live_guard
*** lz_live_gift
*** lz_live_rank
*** lz_live_oss_online
**** lz_live_kylin_home
**** lz_live_bubble_common
**** lz_vod_label
**** lz_common_commservice
**** lz_live_artificialrcmd
**** lz_live_room
**** lz_live_pp_core
**** lz_payment
**** lz_live_medal
**** lz_rec_recommend_platform_model_live
**** lz_live_popularity_guard
**** lz_growth_adfilter
**** lz_live_category
**** lz_sns_relation
@endmindmap