@startmindmap
* 项目
** app_live_comment
*** lz_comment
**** lz_pp_medal
**** lz_vod_verify
**** lz_live_middle_comment
**** lz_live_ban
**** lz_live_fanslevel
**** lz_vod_business
**** lz_live_room
**** lz_live_enternotice
**** lz_payment
**** lz_live_medal
**** lz_live_guard
**** lz_pp_wealth
**** lz_pp_vip
**** lz_live_oss_online
*** lz_live_pp_common
*** lz_pp_ban
*** lz_studio
*** lz_live_middle_comment
*** lz_account_security
*** lz_pp_account
*** lz_live_room
*** lz_live_enternotice
*** lz_live_oss_online
**** lz_live_kylin_home
**** lz_live_bubble_common
**** lz_vod_label
**** lz_common_commservice
**** lz_live_artificialrcmd
**** lz_live_room
**** lz_live_pp_core
**** lz_payment
**** lz_live_medal
**** lz_rec_recommend_platform_model_live
**** lz_live_popularity_guard
**** lz_growth_adfilter
**** lz_live_category
**** lz_sns_relation
** app_sync
*** app_sign
*** app_usersettings
*** lz_playsheet
*** lz_vod_verify
*** lz_voice
*** lz_vod_label
*** lz_common_usercenter
*** lz_common_growth
*** lz_payment
*** lz_studio
*** lz_user_verify
**** lz_datacenter_chat_online
*** lz_sns_relation
*** lz_msg
** app_live_core
*** lz_comment
*** lz_family
*** lz_vod_label
*** lz_common_usercenter
*** lz_live_cover
*** lz_live_category
**** lz_datacenter_chat_online
**** lz_live_room
*** lz_live_room
*** lz_studio
*** lz_user_verify
*** lz_live_category
*** lz_live_channel
*** lz_account_security
@endmindmap