@startmindmap
* VIP功能
** kafka
*** 充值
*** 开通国王
*** 财富等级>=60
** vip名单
*** 新增
**** 手动
**** xxl自动
*** 删除
**** 进入黑名单
*** 修改
** vip黑名单
*** 新增/修改
*** 删除
*** 所有厅号
** vip1
*** 自动发放固定私信
*** 自动发放VIP勋章，发放绿色VIP1勋章
*** 加入VIP名单内
** vip2
*** 送礼飘屏
**** 任务系统-新增条件【单次送礼金额】
*** 小礼物特效
**** 任务系统-用户限制『vip等级』
** vip3
*** 发送vip座驾
*** 发送vip头像框
*** 发送vip气泡
** vip4
*** 任务系统兑换货币新增PP金币
** vip5
*** 礼物冠名
**** 礼物冠名管理
@endmindmap