@startuml
==家族长创建家族==
H5->家族web: 创建家族
家族web --> H5: 返回成功

alt sdk实名认证
H5 -> 业务客户端: 发起实名认证
业务客户端 -> 签约SDK: 发起实名认证
签约SDK -->业务客户端: 返回上上签H5意愿性认证连接跳转到上上签认证
note right
签约SDK无法实时返回实名认证结果
需稍后重新进入查看结果或调用DC接口查询
意愿性认证完成，表示实名成功
end note
end
|||
==家族长合同邀约==
H5 -> 家族web: 获取合同模板id
家族web --> H5: 返回合同模板id
H5 -> 家族web:家族是否实名，没有实名则走sdk实名
家族web --> H5:实名结果
H5 -> 家族web:已实名发起邀约
alt 主播已经实名
家族web -> 家族web: 保存合同信息
家族web -> 签约DC:发送模板合同
家族web --> H5
end
alt 主播未实名
家族web -> 家族web: 保存合同信息
家族web --> H5
end
==家族长和主播签约==
H5 -> 家族web: 判断主播是否实名
note right
主播如果未实名认证
则调用sdk实名认证
end note
家族web --> H5
|||
alt 主播已经实名
|||
H5 -> 业务客户端: 已实名则发起签约
|||
业务客户端 -> 签约SDK: 发起签约
|||
签约SDK--> 业务客户端 : 返回签约H5连接，跳转到上上签签约
note right
签约SDK无法实时返回签约结果
需稍后重新进入查看结果
end note
end

alt 主播未实名
|||
H5 -> 业务客户端: 走实名认证
业务客户端 -> 签约SDK: 走实名认证
|||
H5  -> 家族web: 发起签约
家族web -> 家族web: 获取合同信息
家族web -> 签约DC:发送模板合同
家族web --> H5
|||
alt 家族长/主播签约
H5  -> 业务客户端:获取签约连接
业务客户端 -> 签约SDK: 获取签约连接
|||
签约SDK--> 业务客户端 : 返回签约H5连接，跳转到上上签签约
note right
签约SDK无法实时返回签约结果
需稍后重新进入查看结果
end note
end
end
@enduml