@startuml

业务 -> 签约SDK: 发起实名认证
note right
签约SDK无法实时返回实名认证结果
需稍后重新进入查看结果或调用DC接口查询
end note

业务 -> 签约SDK: 发起合同
业务服务器 --> 业务服务器: 维护家族和主播的资料以及他们之间的关系等信息
|||
业务服务器 --> 签约服务: 建立模板，发起合同
业务服务器 <-- 签约服务: 合同信息
业务服务器 <-- 签约服务: 异步通知合同状态
业务服务器 --> 业务服务器: 同步合同信息，组装合约信息
|||
业务 -> 业务服务器:（根据家族id/主播id）请求合约列表
业务 <- 业务服务器:（根据家族id/主播id）返回对应合约列表
|||
业务 -> 签约SDK: 发起签约
note right
签约SDK无法实时返回签约结果
需稍后重新进入查看结果
end note
@enduml