@startuml
业务客户端 -> 签约SDK: 发起实名认证
签约SDK -->业务客户端: 返回上上签H5意愿性认证连接跳转到上上签认证
note right
签约SDK无法实时返回实名认证结果
需稍后重新进入查看结果或调用DC接口查询
意愿性认证完成，表示实名成功
end note

业务客户端 -> 签约SDK: 发起签约
签约SDK--> 业务客户端 : 返回签约H5连接，跳转到上上签签约
note right
签约SDK无法实时返回签约结果
需稍后重新进入查看结果
end note
@enduml