@startuml
actor 家族长

家族长 -> 家族长后台:发起解约申请
activate 家族长
家族长后台 --> 家族长:发起成功
deactivate 家族长

actor 主播
主播 -> NJ:同意解约


actor 运营人员
运营人员 -> 家族对内后台:同意解约
家族对内后台 ->家族DC:同意解约
家族对内后台 --> NJ:解约成功
家族DC -> 上上签:发送解约合同盖章
上上签 --> 家族DC:异步通知盖章成功
@enduml